---
 - hosts: inventory
   vars:
    date: "{{ lookup('pipe','date +%Y_%m_%d-%H-%M') }}"
   tasks:
    - name: Backup DataBase 
      shell : mysqldump -u root -p'root' GLPI > GLPI--{{ date }}.sql -f
    - name: Fetch the file from the 131 to Master
      fetch: src=/data/Glpi/GLPI--{{ date }}.sql   dest=buffer/ flat=yes
      when: "{{ inventory_hostname == 'host2' }}"

    - name: Copy the file from master to mwiapp02
      copy: src=buffer/glpi2--{{ date }}.sql dest=/tmp/
      when: "{{ inventory_hostname == 'host1' }}"

    - name: Import file.sql similar mysql -u <username> -p <password> < hostname.sql
      mysql_db:
        state: import 
        name: all
        target: /tmp/{{inventory_hostname}}.sql
